In [9]:
import cv2
video=cv2.VideoCapture(0)

while True:
    flag,img=video.read()  # if img exist then flag value will be True else flag value will be false
    if flag==False:
        break
    model_face=cv2.CascadeClassifier("trained model/haarcascade_frontalface_alt.xml")
    Model_eye=cv2.CascadeClassifier("trained model\haarcascade_eye.xml")
    img2=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    face=model_face.detectMultiScale(img2,minNeighbors=14)
    cv2.putText(img,text="Press 'd' to stop",org=(10,20),fontFace=cv2.FONT_HERSHEY_COMPLEX,fontScale=1,color=(0,0,255),thickness=3)
    for x,y,w,h in face:
        cv2.rectangle(img,(x,y,w,h),(0,255,0),2)

        img3=img2[y:y+h,x:x+h]
        eye=Model_eye.detectMultiScale(img3)
        for ex,ey,ew,eh in eye:
            cv2.rectangle(img,(x+ex,y+ey,ew,eh),(0,255,0),2)
    cv2.imshow("wind",img)
    key=cv2.waitKey(50)
    if key==ord('d'):
        break
cv2.destroyAllWindows()
video.release



<function VideoCapture.release>

In [16]:
import cv2
vdo=cv2.VideoCapture(0)
model_face=cv2.CascadeClassifier("trained model/haarcascade_frontalface_alt.xml")
i=1
while True:
    flag,img=vdo.read()
    if flag==False:
        break
    img2=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    face=model_face.detectMultiScale(img2)
    cv2.putText(img,text="Press 'k' to stop",org=(10,20),fontFace=cv2.FONT_HERSHEY_COMPLEX,fontScale=1,color=(0,0,255),thickness=3)
    for x,y,w,h in face:
        cv2.rectangle(img,(x,y,w,h),(0,0,255),2)
        slicing_img=img2[y:y+h,x:x+h]
        cv2.imwrite(f"C:\\Users\DELL\\Desktop\Machine Learning\WD_ML-03-02-2003-\Face_Detection_model\Student\Deepak\img{i}.jpg",slicing_img)
    cv2.imshow("wind",img)
    key=cv2.waitKey(10)
    if key==ord("k"):
        break
cv2.destroyAllWindows()
vdo.release()  

In [26]:
import cv2
vdo=cv2.VideoCapture(0)
Model_face=cv2.CascadeClassifier("trained model\haarcascade_frontalface_alt_tree.xml")
i=1
while True:
    flag,img=vdo.read()
    if flag==False:
        break
    img2=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    face=Model_face.detectMultiScale(img2)
    #cv2.putText(img,text="Press 'k' to stop",org=(10,20),fontFace=cv2.FONT_HERSHEY_COMPLEX,fontScale=1,color=(0,0,255),thickness=3)
    for x,y,w,h in face:
        cv2.rectangle(img,(x,y,w,h),(0,255,0),2)
        slice_face=img2[y:y+h,x:x+w]
        slice_face=cv2.resize(slice_face,(100,100))
        cv2.imwrite(f"Student\Deepak/img{i}.jpg",slice_face)
        i=i+1
    cv2.imshow("wind",img)
    key=cv2.waitKey(20)
    if key==ord("k"):
        break
cv2.destroyAllWindows()
vdo.release()

In [27]:
import cv2
vdo=cv2.VideoCapture(0)
Model_face=cv2.CascadeClassifier("trained model\haarcascade_frontalface_alt_tree.xml")
i=1
while True:
    flag,img=vdo.read()
    if flag==False:
        break
    img2=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    face=Model_face.detectMultiScale(img2)
    #cv2.putText(img,text="Press 'k' to stop",org=(10,20),fontFace=cv2.FONT_HERSHEY_COMPLEX,fontScale=1,color=(0,0,255),thickness=3)
    for x,y,w,h in face:
        cv2.rectangle(img,(x,y,w,h),(0,255,0),2)
        slice_face=img2[y:y+h,x:x+w]
        slice_face=cv2.resize(slice_face,(100,100))
        cv2.imwrite(f"Student\Vivek\img{i}.jpg",slice_face)
        i=i+1
    cv2.imshow("wind",img)
    key=cv2.waitKey(20)
    if key==ord("k"):
        break
cv2.destroyAllWindows()
vdo.release()

In [28]:
import cv2
vdo=cv2.VideoCapture(0)
Model_face=cv2.CascadeClassifier("trained model\haarcascade_frontalface_alt_tree.xml")
i=1
while True:
    flag,img=vdo.read()
    if flag==False:
        break
    img2=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    face=Model_face.detectMultiScale(img2)
    #cv2.putText(img,text="Press 'k' to stop",org=(10,20),fontFace=cv2.FONT_HERSHEY_COMPLEX,fontScale=1,color=(0,0,255),thickness=3)
    for x,y,w,h in face:
        cv2.rectangle(img,(x,y,w,h),(0,255,0),2)
        slice_face=img2[y:y+h,x:x+w]
        slice_face=cv2.resize(slice_face,(100,100))
        cv2.imwrite(f"Student\Pravind\img{i}.jpg",slice_face)
        i=i+1
    cv2.imshow("wind",img)
    key=cv2.waitKey(20)
    if key==ord("k"):
        break
cv2.destroyAllWindows()
vdo.release()

In [29]:
import cv2
vdo=cv2.VideoCapture(0)
Model_face=cv2.CascadeClassifier("trained model\haarcascade_frontalface_alt_tree.xml")
i=1
while True:
    flag,img=vdo.read()
    if flag==False:
        break
    img2=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    face=Model_face.detectMultiScale(img2)
    #cv2.putText(img,text="Press 'k' to stop",org=(10,20),fontFace=cv2.FONT_HERSHEY_COMPLEX,fontScale=1,color=(0,0,255),thickness=3)
    for x,y,w,h in face:
        cv2.rectangle(img,(x,y,w,h),(0,255,0),2)
        slice_face=img2[y:y+h,x:x+w]
        slice_face=cv2.resize(slice_face,(100,100))
        cv2.imwrite(f"Student\Purushotam\img{i}.jpg",slice_face)
        i=i+1
    cv2.imshow("wind",img)
    key=cv2.waitKey(20)
    if key==ord("k"):
        break
cv2.destroyAllWindows()
vdo.release()

In [1]:
import cv2
img=cv2.imread(r"C:\Users\DELL\Desktop\Machine Learning\WD_ML-03-02-2003-\Face_Detection_model\Student\Deepak\img1.jpg",0)
cv2.imshow("window",img)
cv2.waitKey()
cv2.destroyAllWindows()

In [2]:
img.ndim

2

In [3]:
print(img)
print(img.shape)

[[ 23  24  24 ...  32  31  28]
 [ 23  24  25 ...  29  28  26]
 [ 25  25  26 ...  23  23  22]
 ...
 [ 64  64  61 ... 114 112 112]
 [ 62  62  60 ... 114 112 113]
 [ 64  63  60 ... 117 115 116]]
(100, 100)


In [4]:
img.flatten()

array([ 23,  24,  24, ..., 117, 115, 116], dtype=uint8)

In [5]:
len(img.flatten())

10000

In [ ]:
import glob
address=glob.glob(r"C:\Users\DELL\Desktop\Machine Learning\WD_ML-03-02-2003-\Face_Detection_model\Student\Deepak\*.*")
print(address)

In [1]:
import glob
address=glob.glob(r"C:\Users\DELL\Desktop\Machine Learning\WD_ML-03-02-2003-\Face_Detection_model\Student\Deepak\*.*")
address

['C:\\Users\\DELL\\Desktop\\Machine Learning\\WD_ML-03-02-2003-\\Face_Detection_model\\Student\\Deepak\\img1.jpg',
 'C:\\Users\\DELL\\Desktop\\Machine Learning\\WD_ML-03-02-2003-\\Face_Detection_model\\Student\\Deepak\\img10.jpg',
 'C:\\Users\\DELL\\Desktop\\Machine Learning\\WD_ML-03-02-2003-\\Face_Detection_model\\Student\\Deepak\\img100.jpg',
 'C:\\Users\\DELL\\Desktop\\Machine Learning\\WD_ML-03-02-2003-\\Face_Detection_model\\Student\\Deepak\\img101.jpg',
 'C:\\Users\\DELL\\Desktop\\Machine Learning\\WD_ML-03-02-2003-\\Face_Detection_model\\Student\\Deepak\\img102.jpg',
 'C:\\Users\\DELL\\Desktop\\Machine Learning\\WD_ML-03-02-2003-\\Face_Detection_model\\Student\\Deepak\\img103.jpg',
 'C:\\Users\\DELL\\Desktop\\Machine Learning\\WD_ML-03-02-2003-\\Face_Detection_model\\Student\\Deepak\\img104.jpg',
 'C:\\Users\\DELL\\Desktop\\Machine Learning\\WD_ML-03-02-2003-\\Face_Detection_model\\Student\\Deepak\\img105.jpg',
 'C:\\Users\\DELL\\Desktop\\Machine Learning\\WD_ML-03-02-2003-\\Fa

In [39]:
# conversion image into Target & Features
import cv2
x=[]
y=[]

for i in address:
    img=cv2.imread(i,0)
    flattern_img=img.flatten()
    x.append(flattern_img)
    y.append("Deepak")


In [40]:
print(len(address))
len(x[0])

505


10000

In [41]:
print(len(address))
print(len(y))

505
505


In [42]:
print(y)

['Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak', 'Deepak',

In [43]:
address_pur=glob.glob(r"C:\Users\DELL\Desktop\Machine Learning\WD_ML-03-02-2003-\Face_Detection_model\Student\Purushotam\*.*")

In [44]:
for i in address_pur:
    img=cv2.imread(i,0)
    flattern_img=img.flatten()
    x.append(flattern_img)
    y.append("Purushotam")


In [45]:
len(address_pur)

114

In [46]:
print(len(x))
print(len(y))

619
619


In [47]:
505+114

619

In [48]:
print(x[506])
print(y[506])

[27 28 27 ... 71 73 74]
Purushotam


In [49]:
address_viv=glob.glob(r"C:\Users\DELL\Desktop\Machine Learning\WD_ML-03-02-2003-\Face_Detection_model\Student\Vivek\*.*")

In [50]:
for i in address_viv:
    img=cv2.imread(i,0)
    flattern_img=img.flatten()
    x.append(flattern_img)
    y.append("Vivek")


In [51]:
len(address_viv)

532

In [52]:
print(len(x))
print(len(y))

1151
1151


In [53]:
619+532

1151

In [54]:
print(x[-1])
print(y[-1])

[ 27  27  27 ... 172 170 170]
Vivek


In [55]:
address_pra=glob.glob(r"C:\Users\DELL\Desktop\Machine Learning\WD_ML-03-02-2003-\Face_Detection_model\Student\Pravind\*.*")

In [56]:
for i in address_pra:
    img=cv2.imread(i,0)
    flattern_img=img.flatten()
    x.append(flattern_img)
    y.append("Pravind")


In [57]:
len(address_pra)

361

In [58]:
print(len(x))
print(len(y))

1512
1512


In [59]:
1151+361

1512

In [60]:
from sklearn.preprocessing import MinMaxScaler
sc=MinMaxScaler()
x_sc=sc.fit_transform(x)
print(x_sc)


[[0.04504505 0.04977376 0.05357143 ... 0.40465116 0.39814815 0.40277778]
 [0.07657658 0.06334842 0.06696429 ... 0.48837209 0.47685185 0.47222222]
 [0.04954955 0.05429864 0.05357143 ... 0.44186047 0.43518519 0.43518519]
 ...
 [0.83783784 0.8280543  0.8125     ... 0.68372093 0.76851852 0.76388889]
 [0.82432432 0.8280543  0.84821429 ... 0.8        0.79166667 0.51851852]
 [0.82432432 0.83710407 0.58482143 ... 0.76744186 0.80555556 0.64351852]]


In [61]:
len(x[0])

10000

In [62]:
from sklearn.decomposition import PCA
pca=PCA(0.99)
x_pca=pca.fit_transform(x_sc)

In [63]:
x_pca.shape

(1512, 381)

In [64]:
from sklearn.ensemble import AdaBoostClassifier
model=AdaBoostClassifier()   # untrained model
model.fit(x_pca,y)           # Trained model
print("score:",model.score(x_pca,y))

score: 0.8511904761904762


In [65]:
from sklearn.preprocessing import MinMaxScaler
sc=MinMaxScaler()
x_sc=sc.fit_transform(x)
print(x_sc)
from sklearn.decomposition import PCA
pca=PCA(0.99)
x_pca=pca.fit_transform(x_sc)
from sklearn.ensemble import AdaBoostClassifier
model=AdaBoostClassifier()   # untrained model
model.fit(x_pca,y)           # Trained model
print("Accuracy score:",model.score(x_pca,y))


[[0.04504505 0.04977376 0.05357143 ... 0.40465116 0.39814815 0.40277778]
 [0.07657658 0.06334842 0.06696429 ... 0.48837209 0.47685185 0.47222222]
 [0.04954955 0.05429864 0.05357143 ... 0.44186047 0.43518519 0.43518519]
 ...
 [0.83783784 0.8280543  0.8125     ... 0.68372093 0.76851852 0.76388889]
 [0.82432432 0.8280543  0.84821429 ... 0.8        0.79166667 0.51851852]
 [0.82432432 0.83710407 0.58482143 ... 0.76744186 0.80555556 0.64351852]]
Accuracy score: 0.8511904761904762


In [29]:
import cv2
vdo=cv2.VideoCapture(0)
Model_face=cv2.CascadeClassifier("trained model\haarcascade_frontalface_alt_tree.xml")
i=1
while True:
    flag,img=vdo.read()
    if flag==False:
        break
    img2=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    face=Model_face.detectMultiScale(img2)
    cv2.putText(img,text="Press 'k' to stop",org=(10,20),fontFace=cv2.FONT_HERSHEY_COMPLEX,fontScale=1,color=(0,0,255),thickness=3)
    for x,y,w,h in face:
        img2=cv2.resize(img,(100,100))
        img2=img.flatten()
        img2=sc.transform([img2])
        img2=pca.transform(img2)
        result=model.predict(img2)
        cv2.putText(img,text=result[0],org=(10,10),fontFace=cv2.FONT_HERSHEY_COMPLEX,color=(0,0,255),thickness=2,fontScale=1)
        cv2.rectangle(img,(x,y,w,h),(0,255,0),2)
        
    cv2.imshow("wind",img)
    key=cv2.waitKey(20)
    if key==ord("k"):
        break
cv2.destroyAllWindows()
vdo.release()

In [30]:
len(x_pca[0])

381

In [31]:
model.predict([x_pca[0]])

array(['Deepak'], dtype='<U10')

In [32]:
import cv2
vdo=cv2.VideoCapture(0)
Model_face=cv2.CascadeClassifier("trained model\haarcascade_frontalface_alt_tree.xml")
while True:
    flag,img=vdo.read()
    if flag==False:
        break
    img2=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    face=Model_face.detectMultiScale(img2)
    cv2.putText(img,text="Press 'k' to stop",org=(10,20),fontFace=cv2.FONT_HERSHEY_COMPLEX,fontScale=1,color=(0,0,255),thickness=3)
    for x,y,w,h in face:
        cv2.rectangle(img,(x,y,w,h),(0,255,0),2)
        im3=img2[y:y+h,x:x+w]
        img_resize=cv2.resize(im3,dsize=(100,100))
        img_flatten=img_resize.flatten()
        img_sc=sc.transform([img_flatten])
        img_pca=pca.transform(img_sc)
        result=model.predict(img_pca)
        cv2.putText(img,text=result[0],org=(x+10,y+10),fontFace=cv2.FONT_HERSHEY_COMPLEX,color=(0,0,255),thickness=2,fontScale=1)
        #result2=model.predict_proba(img_pca)
        #cv2.putText(img,text=f"{np.max(result2)}",org=(x+10,y+40),fontFace=cv2.FONT_HERSHEY_COMPLEX,color=(0,0,255),thickness=2,fontScale=1)
        
        
    cv2.imshow("wind",img)
    key=cv2.waitKey(20)
    if key==ord("k"):
        break
cv2.destroyAllWindows()
vdo.release()

In [35]:
import cv2
vdo=cv2.VideoCapture(0)
Model_face=cv2.CascadeClassifier("trained model\haarcascade_frontalface_alt_tree.xml")
i=1
while True:
    flag,img=vdo.read()
    if flag==False:
        break
    img2=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    face=Model_face.detectMultiScale(img2)
    #cv2.putText(img,text="Press 'k' to stop",org=(10,20),fontFace=cv2.FONT_HERSHEY_COMPLEX,fontScale=1,color=(0,0,255),thickness=3)
    for x,y,w,h in face:
        cv2.rectangle(img,(x,y,w,h),(0,255,0),2)
        im3=img2[y:y+h,x:x+w]
        img_resize=cv2.resize(im3,dsize=(100,100))
        img_flatten=img_resize.flatten()
        img_sc=sc.transform([img_flatten])
        img_pca=pca.transform(img_sc)
        result=model.predict(img_pca)
        cv2.putText(img,text=result[0],org=(10,20),fontFace=cv2.FONT_HERSHEY_COMPLEX,fontScale=1,color=(0,0,255),thickness=3)
        result2=model.predict_proba(img_pca)
        cv2.putText(img,text=result[0],org=(10,20),fontFace=cv2.FONT_HERSHEY_COMPLEX,fontScale=1,color=(0,0,255),thickness=3)

        
        
    cv2.imshow("wind",img)
    key=cv2.waitKey(20)
    if key==ord("k"):
        break
cv2.destroyAllWindows()
vdo.release()

In [37]:
import numpy as np
["Deepak","Pravind","Purushotam","Vivek"]
np.argmax([0.8,0.02,0.06,0.03])


0

In [67]:
x

[array([ 23,  24,  24, ..., 117, 115, 116], dtype=uint8),
 array([ 30,  27,  27, ..., 135, 132, 131], dtype=uint8),
 array([ 24,  25,  24, ..., 125, 123, 123], dtype=uint8),
 array([ 22,  23,  23, ..., 137, 132, 130], dtype=uint8),
 array([ 24,  25,  25, ..., 136, 131, 128], dtype=uint8),
 array([ 25,  23,  23, ..., 129, 125, 123], dtype=uint8),
 array([ 25,  25,  24, ..., 131, 126, 124], dtype=uint8),
 array([ 25,  25,  24, ..., 131, 126, 124], dtype=uint8),
 array([ 24,  25,  25, ..., 130, 124, 121], dtype=uint8),
 array([ 23,  24,  24, ..., 126, 123, 121], dtype=uint8),
 array([ 24,  23,  21, ..., 132, 127, 123], dtype=uint8),
 array([ 24,  25,  25, ..., 132, 128, 129], dtype=uint8),
 array([ 27,  27,  27, ..., 126, 125, 124], dtype=uint8),
 array([ 24,  25,  26, ..., 130, 127, 125], dtype=uint8),
 array([ 24,  24,  24, ..., 130, 127, 125], dtype=uint8),
 array([ 21,  22,  23, ..., 128, 123, 119], dtype=uint8),
 array([ 23,  24,  24, ..., 132, 129, 127], dtype=uint8),
 array([ 24,  

In [68]:
set(y)

{'Deepak', 'Pravind', 'Purushotam', 'Vivek'}

In [69]:
import pandas as pd

In [72]:
z=pd.DataFrame(y)
z

0
0      Deepak
1      Deepak
2      Deepak
3      Deepak
4      Deepak
...       ...
1507  Pravind
1508  Pravind
1509  Pravind
1510  Pravind
1511  Pravind

[1512 rows x 1 columns]

In [73]:
z[0].value_counts()

Vivek         532
Deepak        505
Pravind       361
Purushotam    114
Name: 0, dtype: int64

In [74]:
z[0].value_counts().index

Index(['Vivek', 'Deepak', 'Pravind', 'Purushotam'], dtype='object')

In [79]:
import cv2
import numpy as np
vdo=cv2.VideoCapture(0)
Model_face=cv2.CascadeClassifier("trained model\haarcascade_frontalface_alt_tree.xml")
i=1
while True:
    flag,img=vdo.read()
    if flag==False:
        break
    img2=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    face=Model_face.detectMultiScale(img2)
    #cv2.putText(img,text="Press 'k' to stop",org=(10,20),fontFace=cv2.FONT_HERSHEY_COMPLEX,fontScale=1,color=(0,0,255),thickness=3)
    for x,y,w,h in face:
        cv2.rectangle(img,(x,y,w,h),(0,255,0),2)
        im3=img2[y:y+h,x:x+w]
        img_resize=cv2.resize(im3,dsize=(100,100))
        img_flatten=img_resize.flatten()
        img_sc=sc.transform([img_flatten])
        img_pca=pca.transform(img_sc)
        result=model.predict(img_pca)
        cv2.putText(img,text=result[0],org=(x+10,y+20),fontFace=cv2.FONT_HERSHEY_COMPLEX,fontScale=1,color=(0,0,255),thickness=3)
        result2=model.predict_proba(img_pca)
        print(result2[0])
        cv2.putText(img,text=f"{np.max(result2)}",org=(x+10,y+40),fontFace=cv2.FONT_HERSHEY_COMPLEX,fontScale=1,color=(0,0,255),thickness=3)

        
        
    cv2.imshow("wind",img)
    key=cv2.waitKey(20)
    if key==ord("k"):
        break
cv2.destroyAllWindows()
vdo.release()

[3.55296549e-01 3.67729332e-01 1.81044048e-04 2.76793075e-01]
